# https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-cli-command-reference.html
AVAILABLE_CMDS = [
    "cheat-sheet",
    "connections add",
    "connections delete",
    "dags delete",
    "dags list-jobs",
    "dags pause",
    "dags report",
    "dags show",
    "dags state",
    "dags test",
    "dags trigger",
    "dags unpause",
    "providers behaviours",
    "providers get",
    "providers hooks",
    "providers links",
    "providers list",
    "providers widgets",
    "roles create",
    "roles list",
    "tasks clear",
    "tasks failed-deps",
    "tasks list",
    "tasks render",
    "tasks state",
    "tasks states-for-dag-run",
    "tasks test",
    "variables delete",
    "variables get",
    "variables set",
    "variables list",
    "version",
]
